#!/bin/bash

echo
echo
echo "********************************"
echo "Running ggyatm..."
echo 
echo
echo "Downloading required files..."
curl -s -o gyatm http://justinthompson593.github.io/Public/gyatm/gyatm

echo
echo "Modifying..."
chmod +x gyatm

echo
echo "Running gyatm"
./gyatm

echo
echo "Done."
echo "********************************"






















