#!/bin/bash 

mkdir ~/Passwords

cd ~/Passwords

touch passwords.txt

echo "Would you like to add a password to your safe (y/n)? "
read usrIn

while [ "$usrIn" == "y" ]
do
	echo "Enter a title for the password (Bank, Emailname1, Emailname2, etc.): "
	read usrIn
	echo "$usrIn" >> passwords.txt
	echo "Enter the username (myusername, myemail@gmail.com, etc.): "
	read usrIn
	echo "username: $usrIn" >> passwords.txt
	echo "Enter the password: "
	read usrIn
	echo "password: $usrIn" >> passwords.txt
	echo "Would you like to add a password to your safe (y/n)? "
	read usrIn
done
