#!/bin/bash 

echo "Installing Password Safe"

#sudo apt-get install curl pgpgpg

mkdir ~/PasswordSafe

cd ~/PasswordSafe

curl -o PS.cpp http://justinthompson593.github.io/SoftwareDrop/PasswordSafe.cpp

g++ PS.cpp -o PasswordSafe && rm PS.cpp

echo "export PATH=$PWD:$PATH" >> ~/.bashrc

touch passwords.txt

echo
echo
echo "Would you like to add a password to your safe? You will have the option to add new passwords and info  (y/n)? "
read usrIn

while [ "$usrIn" == "y" ]
do
	echo "Enter a title for the password (Bank, Phone, Internet, Gmail, Hotmail, etc.): "
	read usrIn
	Title="$usrIn"
	echo "$Title" >> passwords.txt
	echo "Enter the username (myusername, myemail@whatever.com, etc.): "
	read usrIn
	uName="$usrIn"
	echo "username: $uName" >> passwords.txt
	echo "Enter the password: "
	read usrIn
	echo "password: $usrIn" >> passwords.txt
	echo "Are there any notes you'd like to have under the title $Title?"
	echo "Your information could, for instance, like this:"
	echo ""
	echo "$Title"
	echo "username: $uName"
	echo "password: $usrIn"
	echo -e "Notes:\n\tsecurity question answer: Bingo"
	echo -e "\tPin: 12345"
	echo ""
	echo "Enter y to add a note to $Title"
	read usrIn
	if [ "$usrIn" == "y" ]
	then
		echo "Notes:" >> passwords.txt
	fi
	while [ "$usrIn" == "y" ]
	do
		echo "Enter your note in quotes (i.e. \"Pin: 12345\" or \"security word is black\"):"
		read usrIn
		echo -e "\t$usrIn" >> passwords.txt
		echo "Enter y to add another note to $Title"
		read usrIn
	done
	echo "" >> passwords.txt
	echo "Would you like to add another password to your safe (y/n)? "
	read usrIn
done

clear
echo
echo
echo "Now get ready to choose a master passphrase for your safe. You will be asked to type it in twice."
echo

gpg -c --cipher-algo AES256 passwords.txt && rm passwords.txt

